# Network
GAMECONTROLLER_PORT = 3838
GAMECONTROLLER_STRUCT_HEADER = "RGme"
GAMECONTROLLER_STRUCT_VERSION = 8
MAX_NUM_PLAYERS = 11

# Team colors
TEAM_BLUE = 0
TEAM_CYAN = 0
TEAM_RED = 1
TEAM_MAGENTA = 1
DROPBALL = 2

# Game states
STATE_INITIAL = 0
STATE_READY = 1
STATE_SET = 2
STATE_PLAYING = 3
STATE_FINISHED = 4

# Secondary states
STATE2_NORMAL = 0
STATE2_PENALTYSHOOT = 1
STATE2_OVERTIME = 2
STATE2_TIMEOUT = 3

# Penalties
PENALTY_NONE = 0
PENALTY_SPL_BALL_HOLDING = 1
PENALTY_SPL_PLAYER_PUSHING = 2
PENALTY_SPL_OBSTRUCTION = 3
PENALTY_SPL_INACTIVE_PLAYER = 4
PENALTY_SPL_ILLEGAL_DEFENDER = 5
PENALTY_SPL_LEAVING_THE_FIELD = 6
PENALTY_SPL_PLAYING_WITH_HANDS = 7
PENALTY_SPL_REQUEST_FOR_PICKUP = 8
PENALTY_SPL_COACH_MOTION = 9

# Return message types
GAMECONTROLLER_RETURN_STRUCT_HEADER = "RGrt"
GAMECONTROLLER_RETURN_STRUCT_VERSION = 2
GAMECONTROLLER_RETURN_MSG_MAN_PENALISE = 0
GAMECONTROLLER_RETURN_MSG_MAN_UNPENALISE = 1
GAMECONTROLLER_RETURN_MSG_ALIVE = 2

SPL_COACH_MESSAGE_SIZE = 40

# State name mappings
STATE_NAMES = {
    STATE_INITIAL: "INITIAL",
    STATE_READY: "READY",
    STATE_SET: "SET", 
    STATE_PLAYING: "PLAYING",
    STATE_FINISHED: "FINISHED"
}

PENALTY_NAMES = {
    PENALTY_NONE: "NONE",
    PENALTY_SPL_BALL_HOLDING: "BALL_HOLDING",
    PENALTY_SPL_PLAYER_PUSHING: "PLAYER_PUSHING",
    PENALTY_SPL_OBSTRUCTION: "OBSTRUCTION",
    PENALTY_SPL_INACTIVE_PLAYER: "INACTIVE_PLAYER",
    PENALTY_SPL_ILLEGAL_DEFENDER: "ILLEGAL_DEFENDER",
    PENALTY_SPL_LEAVING_THE_FIELD: "LEAVING_THE_FIELD",
    PENALTY_SPL_PLAYING_WITH_HANDS: "PLAYING_WITH_HANDS",
    PENALTY_SPL_REQUEST_FOR_PICKUP: "REQUEST_FOR_PICKUP",
    PENALTY_SPL_COACH_MOTION: "COACH_MOTION"
}
